### ISSUE TITLE
UPDATE_REQUIRED but there is no update button

### ISSUE THREAD

**Issue by colourful-land** [Bertrand256/dash-masternode-tool#17]
DashMasterTool displays "UPDATE_REQUIRED" in red colour for Status. This is what I did.

1. I updated DashMasterTool to the latest edition (0.9.20) but the red status remains.

2. I thought maybe it means the node's software needs to be updated. Then I updated dashd to the latest edition 0.12.3 and restarted dash node. The red status remains.

3. Maybe the node need to update the latest blockchain? No clue this end.

4. Maybe there is an update button? Didn't find one.

5. Maybe I need to click the button "start masternode using hardware wallet?" But it didn't complain "RESTART_REQUIRED"

6. Maybe it means that the information displayed in Dash Masternode Tool is outdated and I need to update it? So I clicked "Get Status" and the message remains.

Anyway, the user interface of DashMasterTool is extremely confusing. It's like meeting God. God says "it ended" then send me back to live. So what does the God mean? My life has ended? My punishment is over? The session to meet God has ended? My redemption has ended so I just need to live my life till death without damaging krama any more?

Software developers often feel like God and hope one word is all they need to communicate with users. "Update". That's it, you got what I said, update. If you don't know what UPDATE means, you probably shouldn't be running a masternode. Is that so?

**Comment by Bertrand256** [comment]
Thank you for your comments. I try to make the tool as simple as possible for the user but the basic assumption is a good knowledge of what is masternode, how to configure it, how to deal with the problems encountered, how to understand individual statuses returned by masternode, and fluency in using hardware wallet depending on what device you are connecting the program to (Trezor, Ledger, Keepkey).

The program in no way aims to perform an educational role, not only because of the lack of resources, but also due to the very wide technological scope touching by it, which additionally is subject to constant changes. Acquiring knowledge in these areas is entirely on the user's side.

As for the statuses displayed in the "Masternode status" field - these are messages returned by the masternode itself, and the program only displays them without interpreting them in any way. Their meaning should be checked in the documentation, for example here: https://docs.dash.org/en/latest/masternodes/setup.html#start-your-masternode. If you don't find description for a particular status, please ask the community.

Status "UPDATE_REQUIRED" means that your node's dashd reports the protocol version not supported by the network anymore. If you do not upgrade the node, your masternode will be excluded from the payment queue.

Status "NEW_START_REQUIRED" means that you must send the "Start masternode" message for that masternode or it will be excluded from the payment queue. The reason may be, for example, upgrading the Dash daemon version without  subsequent sending the "start" message, or the lack of visibility of your masternode in the network for more than 3 hours.
