### ISSUE TITLE
 Bertrand256

### ISSUE THREAD

**Issue by itsmorelove** [Bertrand256/dash-masternode-tool#47]
Thank you for your help.

This ticket seems to be related to where I am having trouble: https://github.com/Bertrand256/dash-masternode-tool/issues/35 

Could you help me get the DMT to read the Trezor? 

I am working with 2 accounts. 1 on my computer MacOS and a different Trezor on Windows 10. We are both having the same problem. You recommend installing the Trezor Bridge or running the DMT as administrator. Do you have any other recommendations for us?

1. How do you run the DMT as administrator? 
2. On the Mac, I downloaded the bridge, updated Trezor firmware, and downloaded the latest version of the DMT v 9.32. I am still not seeing my Dash wallet. I hope you can see my screen-shot attached.

<img width="1346" alt="Screen Shot 2022-09-20 at 2 42 40 PM" src="https://user-images.githubusercontent.com/114021796/191342912-8dac2a71-baaf-4e6a-b0da-b8457d614c56.png">

**Comment by itsmorelove** [comment]
App Log for MacOS

https://docs.google.com/document/d/1eeJVXEKk2wYW3fZRCaR2tlETmW4cZRrks1-vgvm4yvY/edit?usp=sharing

**Comment by Bertrand256** [comment]
From your logs, it appears that the Trezor device is busy while DMT is trying to communicate with it. Make sure no other application is running that could be communicating with Trezor, such as Trezor Live, Electrum or even the Brave browser (which also has a built-in hardware wallet interface).

**Comment by itsmorelove** [comment]
Thank you for this. 

I quit my web browsers and Trezor suite, and then connected my Trezor to the DMT. It took some time fetching transactions and never connected. I tried again and still did not populate my transactions. I am curious because I use Trezor suite. I am always sure it is quit before connecting to DMT. I do not have Electrum or Brave browser. What else could be communicating with my Trezor?

Here is the log from today:

2022-09-22 08:12:23 INFO|root|MainThread|app_config.py|init|===========================================================================
2022-09-22 08:12:23 INFO|root|MainThread|app_config.py|init|Application started (v 0.9.32)
2022-09-22 08:12:23 INFO|root|MainThread|app_config.py|init|Environment:
2022-09-22 08:12:23 INFO|root|MainThread|app_config.py|init|environ({'USER': 'katieelliott', '__CFBundleIdentifier': 'DashMasternodeTool', 'COMMAND_MODE': 'unix2003', 'LOGNAME': 'katieelliott', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.eVAAFlM1qJ/Listeners', 'SHELL': '/bin/bash', 'HOME': '/Users/katieelliott', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'TMPDIR': '/var/folders/fv/w5d8r1bs1ys58xy723cqgyv00000gn/T/', 'XPC_SERVICE_NAME': '0', 'XPC_FLAGS': '0x0', 'QT_PLUGIN_PATH': '/var/folders/fv/w5d8r1bs1ys58xy723cqgyv00000gn/T/_MEIeeJuot/PyQt5/Qt5/plugins', 'QML2_IMPORT_PATH': '/var/folders/fv/w5d8r1bs1ys58xy723cqgyv00000gn/T/_MEIeeJuot/PyQt5/Qt5/qml', 'TCL_LIBRARY': '/var/folders/fv/w5d8r1bs1ys58xy723cqgyv00000gn/T/_MEIeeJuot/tcl', 'TK_LIBRARY': '/var/folders/fv/w5d8r1bs1ys58xy723cqgyv00000gn/T/_MEIeeJuot/tk', 'QT_API': 'pyqt5'})
2022-09-22 08:12:24 INFO|root|MainThread|main_dlg.py|setupUi|Finished setup of the main dialog.
2022-09-22 08:35:00 INFO|root|MainThread|app_config.py|init|===========================================================================
2022-09-22 08:35:00 INFO|root|MainThread|app_config.py|init|Application started (v 0.9.32)
2022-09-22 08:35:00 INFO|root|MainThread|app_config.py|init|Environment:
2022-09-22 08:35:00 INFO|root|MainThread|app_config.py|init|environ({'USER': 'katieelliott', '__CFBundleIdentifier': 'DashMasternodeTool', 'COMMAND_MODE': 'unix2003', 'LOGNAME': 'katieelliott', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.T2jfiZDmxA/Listeners', 'SHELL': '/bin/bash', 'HOME': '/Users/katieelliott', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'TMPDIR': '/var/folders/fv/w5d8r1bs1ys58xy723cqgyv00000gn/T/', 'XPC_SERVICE_NAME': '0', 'XPC_FLAGS': '0x0', 'QT_PLUGIN_PATH': '/var/folders/fv/w5d8r1bs1ys58xy723cqgyv00000gn/T/_MEIJi6zCZ/PyQt5/Qt5/plugins', 'QML2_IMPORT_PATH': '/var/folders/fv/w5d8r1bs1ys58xy723cqgyv00000gn/T/_MEIJi6zCZ/PyQt5/Qt5/qml', 'TCL_LIBRARY': '/var/folders/fv/w5d8r1bs1ys58xy723cqgyv00000gn/T/_MEIJi6zCZ/tcl', 'TK_LIBRARY': '/var/folders/fv/w5d8r1bs1ys58xy723cqgyv00000gn/T/_MEIJi6zCZ/tk', 'QT_API': 'pyqt5'})
2022-09-22 08:35:02 INFO|root|MainThread|main_dlg.py|setupUi|Finished setup of the main dialog.

**Comment by Bertrand256** [comment]
I apologize for the delay, but I've been testing various things because I'm having trouble identifying what might be the cause. 

I have a few questions:
1. Please confirm  if I understood correctly that the problem occurs on both Mac and Windows.
2. Are these Mac and Windows separate computers, or are they the same machine?
3. Does the Trezor Live app work correctly with the same Trezor device, i.e. does it show the balances you expect?
4. Have you tried changing Trezor's USB cable to a different one?

**Comment by itsmorelove** [comment]
Yes it occurs on both Mac & Windows. Separate computers. This is two isolated cases. I help manage a different user through video, screen-share help. They have their own Trezor and use Windows. I have my Mac computer and my Trezor. I do not have has much freedom to trouble shoot on the Windows. So when I refer to mine and "I", I am using Mac. 
 
Yes the Trezor suite is showing balances expected for both users.

A different USB cable is giving me the same result, no transactions. 

Additional information. I downloaded the DMT onto a different Mac and had the same problem. Also, I have 2 Trezors here with me to connect to the Macs. One Trezor is connecting fine.

**Comment by Bertrand256** [comment]
> Additional information. I downloaded the DMT onto a different Mac and had the same problem. Also, I have 2 Trezors here with me to connect to the Macs. One Trezor is connecting fine.

Just to be sure: does the other Trezor work correctly with the DMT application on your Mac, in particular, does it show the correct balances? Do both Trezors have the same seed configured?

What is the firmware version of this non-working Trezor? You can read it from within Trezor Live.
Thanks.

**Comment by itsmorelove** [comment]
Two different Trezors. Two different seed configurations. One works as expected in the DTM, the balances are what is expected. One does not (no transactions found).

I am running firmware v 1.11.2

**Comment by Bertrand256** [comment]
The issue is so problematic that you will need to compare the Dash addresses that DMT shows with the address that Trezor Suite shows for the same index. If you can do that it would be great. Just remember that Trezor Suite and DMT should not be running at the same time. Below I show with images what steps you should follow.

1. First, open wallet in DMT

2. Read the Dash address for index 0/0
![image](https://user-images.githubusercontent.com/9880025/192873476-eaf8dc1c-a377-4a4b-8d7f-dc2f4f74ad51.png)

3. Close DMT and start Trezor Suite. The only way I have found that allows you to read the Dash address for a specific index in this application is to use the message signing feature, so run it:
![image](https://user-images.githubusercontent.com/9880025/192873867-444026fa-fc82-42ea-998a-0485e5abfa5b.png)

4. Select the address for index 0:
![image](https://user-images.githubusercontent.com/9880025/192874015-5009bea8-050a-41e6-a87d-6fb3f9f9b79c.png)

5. Reveal the whole address:
![image](https://user-images.githubusercontent.com/9880025/192874082-7b7d25dd-5582-45ac-b4b2-575dd4478dea.png)

6. Get the address and compare it with the one you've got in step 2:
![image](https://user-images.githubusercontent.com/9880025/192874254-6e0fa78f-34bf-4070-ac9a-31cec228dcb1.png)

Please let me know whether the addresses from step 2 and 6 are equal or not. Do not paste anything private here, such as your real Dash addresses.

**Comment by itsmorelove** [comment]
Checking in.

Would restoring the Trezor and starting from scratch with my recovery seed do the trick?

Thank you!

**Comment by Bertrand256** [comment]
Oops, thanks for the reminder.  

> Would restoring the Trezor and starting from scratch with my recovery seed do the trick?
Unfortunately this is unlikely to help, but what I was going to ask you is whether you use passphrase for your trezor and if so, does it have any non-English (i.e. non ASCII) characters?

**Comment by itsmorelove** [comment]
I do not use a passphrase, but sometimes it does ask me for one. When it does, I enter my pin as the passphrase. It seemingly accepts it.

**Comment by Bertrand256** [comment]
Here is probably the cause of the problem. The point is that the passphrase used in hardware wallets (BIP39) works differently than a typical password to protect access to something. Generally, any passphrase will be correct, because any passphrase opens a kind of hidden wallet, giving you completely different set of Dash addresses for each passphrase. Here's an article describing how it works: https://blog.trezor.io/passphrase-the-ultimate-protection-for-your-accounts-3a311990925b.

What's puzzling is why, as you've written, sometimes it asks for a password and sometimes it doesn't. It's a configuration option and if it's not set, the passphrase dialog shouldn't come up. I suggest you check the status of this setting. 

This can be done from DMT by following these steps:

1. Click the Toolbox button
![image](https://user-images.githubusercontent.com/9880025/195690528-9517f177-fc7f-477f-bc01-49b2cbbceb80.png)

2. Then click `Hardware wallet settings`
![image](https://user-images.githubusercontent.com/9880025/195690583-def0429d-7b62-4b78-acb2-5f2e180cf8a1.png)

3. And finally, you will see all the settings of your Trezor
![image](https://user-images.githubusercontent.com/9880025/195690782-9b6f55e2-d746-4d0c-bce5-8b07eaf34f92.png)

Note whether the Passphrase option is on or off. If it's off and the app nevertheless sometimes asks for a passphrase, it means there's most likely a problem with either the device or the firmware - the passphrase dialog is invoked by the Trezor library, so it probably isn't related to DMT itself. 

Regardless, the next time the app asks you for a passphrase, do not enter your PIN (or anything else) but instead leave the passphrase field blank. The effect will be as if you had the password option disabled.

Btw. does the Trezor suite also sometimes ask you for passphrase or never?

**Comment by itsmorelove** [comment]
🎉🎉🎉

Passphrase was enabled. I disabled it in the hardware settings. PROBLEM SOLVED! I really appreciate your responsiveness and working with me on this. MUCH gratitude, thank you!

When passphrase was enabled in the DMT, the Trezor Suite requested me to select wallet type (see attached image). If I chose Standard wallet, no passphrase was needed. I confirmed: changing the passphrase setting in the DMT automatically changed the settings in the Trezor suite. Once passphrase was disabled, the Trezor Suit no longer asked for my wallet type.

![Screen Shot 2022-10-13 at 4 02 07 PM](https://user-images.githubusercontent.com/114021796/195701321-b629c4e4-fee0-4582-875b-ee05bd0334f6.png)

**Comment by Bertrand256** [comment]
> Also, I tried to just skip the passphrase without disabling the setting. I x'd out of the passphrase box. The DMT would not let me continue. It gives me a cancelled notification.

Stopping with an error is intentional in such a situation. If the user has the password option enabled for their Trezor, then they must enter it, even if it were a blank password. Trying to bypass the password by clicking "cancel" is treated as an abandonment of performing this operation at this point.

We are dealing with financial assets here, so the device must be sure that the user knows what he is doing. In such a situation, it is better to enter a blank passphrase and confirm it with the OK button - then it will behave as if he had the passphrase option turned off.

**Comment by itsmorelove** [comment]
Yes, I see this behavior playing around with settings. I was entering my pin as my passphrase (so an incorrect passphrase) and was under the impression it was accepting it because I didn't get any kind of error.

Again, thanks for your help! I will close this ticket.
