### ISSUE TITLE
Payload missmatch

### ISSUE THREAD

**Issue by vampyren** [Bertrand256/dash-masternode-tool#50]
Hi, 
Last night trying to start a MN was almost impossible. Had to restart multiple times and connect/disconnect ledger before it suddenly started working ....kept getting this error:
![image](https://github.com/Bertrand256/dash-masternode-tool/assets/4087127/a53fd805-3dc3-4dd8-880c-c0dd6ef21eeb)

I try to register using allnode + DMT+ my own wallet to sign.  Also it asked med multiple time to accept several addresses. Seen this happen a few times when something goes wrong. 

In general DMT is pretty unstable when it comes to interacting with ledger!

**Comment by Bertrand256** [comment]
The problem with the Ledger is that its firmware does not support Testnet Dash, so this makes it virtually impossible to perform any meaningful tests with this hardware wallet. 

However, the app's behavior you describe looks like typical interference of the communication between DMT and the Ledger itself by another application that is communicating with the device at the same time. That other application could be Ledger Live, but also web browsers like Brave Browser, which have hardware wallet support implemented and may try to communicate with the device at the time you are trying to use it within DMT. Please make sure that this situation does not apply to you.

Btw, I will be publishing a new version of DMT in the next few days, so you can try if it changes anything in this matter.

**Comment by vampyren** [comment]
I always make sure i don't have Ledger Live open when i use DMT so i don't think that is it. Also don't have anything that connect to ledger. Atleast on the PC i use metamask isn't connected to hw wallet or anything. 
I tried the new version and so far it works ok. I do however see these warnings i did not before: 
![image](https://github.com/Bertrand256/dash-masternode-tool/assets/4087127/26580a2b-185c-41a7-81ce-b85fbee98dbe)

Trying to use the "Update operator Key" gave this:
![image](https://github.com/Bertrand256/dash-masternode-tool/assets/4087127/8771a73d-b56a-4541-917c-746eb2bb45a4)
And sometime it shows this:
![image](https://github.com/Bertrand256/dash-masternode-tool/assets/4087127/00630996-0553-4eb7-9935-6e1f17b31ba9)

**Comment by Bertrand256** [comment]
Thanks for the update. This kind of problem ("Private key for owner .... not found in your wallet" suggests that you are not using so-called public RPC nodes to connect to the Dash network but rather some node of your own.

The configuration for "Public" nodes should look like this:
![image](https://github.com/Bertrand256/dash-masternode-tool/assets/9880025/2d7348fe-610a-4d77-8f1b-08c600a8e287)

Can you check if this is actually the case? 
If you're using your own node, you have do import your owner private key into the node's wallet. Here it is also worth noting that even if you have two public nodes in the configuration but also in addition you have your own one(s), you also need to perform this step (importing the owner privkey), because DMT randomly selects connection configurations from all active ones as a kind of a load balance mechanism.

Anyway, if you only have public RPC nodes in your configuration please let me know, as this would indicate some problems at the software level of this public RPC server.

**Comment by vampyren** [comment]
Thanks for the nice info. And your right i use my own node (just 1 core wallet). 
On the other hand i have not enabled SSL + i have not added RPC private/public key. I check the guide and can't find how to do so.
https://docs.dash.org/en/stable/docs/user/wallets/dashcore/advanced.html

Can you please let me know how i can do this part? 

I tried to add the the following in the dash.conf  and found a funny bug when restarting the core wallet :)
masternodeblsprivkey=...
masternodeblsprivkey=...
![image](https://github.com/Bertrand256/dash-masternode-tool/assets/4087127/73a727d3-cede-46cf-989b-f7ce03ea98c8)

But going back to the RPC issue, please let me know how i can do this. I have before used PUTTYGEN.EXE to create public/private keys but seems when i try to put the public key from putty in DMT it fails
![image](https://github.com/Bertrand256/dash-masternode-tool/assets/4087127/cb5f24b9-d4a1-4950-95d4-44588eefd807)

Sorry i'm a bit lost here.

**Comment by Bertrand256** [comment]
When it comes to that "**RPC encryption public key**" option, it is only used with "**public**" RPC nodes. They (the nodes) have an additional encryption layer (besides SSL) to additionally protect the client's keys during their transmission for the use with the `protx update_registrar/update_service` calls. This aspect is touched [here](https://github.com/Bertrand256/dash-masternode-tool/blob/master/doc/registering-masternode.md#scenario-1-automatic-method-using-public-rpc-nodes).

So, when using your own RPC node, leave the "RPC encryption public key" empty in your configuration. Also, if you are connecting to hour dash daemon directly (i.e. without any intermediate http server like nginx/apache), leave the SSL checkbox unchecked, otherwise it won't work, since Dash supports plain HTTP.

Can you expand the topic related to "masternodeblsprivkey=" issue? I don't quite understand what's you concern. 

You probably know this, but to avoid possible problems if it turned out otherwise, I have to note, that the `masternodeblsprivkey` setting should only bo done in your masternode's dash.con file, but not in that one from you RPC node. On your masternode, you should place there your operator **private key** associated with the operator **public key**, that was sent during the masternode registration (or the update_service call).

**Comment by vampyren** [comment]
Thanks for info. I get the idea that the key's are for protecting the data being sent between the nodes. So in my case i guess i'm not sure then what do i need to do for getting rid of the warning? (sorry maybe you answer this but i did not get it )
By the way i use allnode right now so the MN is handled by them. 

I have also followed exactly as this page says and connected test is OK
https://github.com/Bertrand256/dash-masternode-tool/blob/master/doc/config-connection-direct.md

About the "masternodeblsprivkey=", i don't know why i put it the file to be honest :) but this made the dash wallet behave as you can see in the picture....you can't get into the wallet basically. The "Tools windows" will be shown as the main window and you can't get around it.

**Comment by Bertrand256** [comment]
> So in my case i guess i'm not sure then what do i need to do for getting rid of the warning?

You mean the "Private key for owner not found in your wallet" or "Protx signature payload mismatch" warning, or maybe something else? Sorry, I suppose I got a bit desynchronized from the esence of your message. 

> About the "masternodeblsprivkey=", i don't know why i put it the file to be honest :) but this made the dash wallet behave as you can see in the picture....you can't get into the wallet basically. 

This is indeed interesting. You might consider reporting this problem to the Dash Github repo.

**Comment by vampyren** [comment]
Just wondering do i need to do anything for the warnings and if so what (cause i'm also a bit confused now :)) 
![image](https://github.com/Bertrand256/dash-masternode-tool/assets/4087127/643ffdd5-9083-4104-9590-4d42db095aee)

I can report the second in Dash repo. Thanks!

**Comment by vampyren** [comment]
Awesome! thanks a bunch for the help and quick updates! 
Cheers!
